Continuous Integration - Continuous Deployment / Delivery - Phase II

diff --git a/management/:w b/management/:w
--- a/management/:w
+++ b/management/:w
@@ -181,10 +181,10 @@ function file_owner () {
 function install_git_distribution () {
     module_name="$1"
 
-    [ -z "${module_name}" ] && die "[install_git_distribution] Usage: install_git_distribution <module_name>"
+    [ -z "${module_name}" ] && die "Usage: install_git_distribution <module_name>"
 
     set ${INITIAL_RELEASE["${module_name}"]}
-    [ $# -ne 3 ] && die "[install_git_distribution] Invalid git module specification:[${INITIAL_RELEASE["${module_name}"]}]"
+    [ $# -ne 3 ] && die "Invalid git module specification:[${INITIAL_RELEASE["${module_name}"]}]"
 
     repos_name="$1"
     branch_name="$2"
@@ -241,7 +241,7 @@ function bootstrap_module () {
         $DO  mkdir -p "${install_dir}"
         newdir_flag=1
     fi
-    $DO cd "${install_dir}" || die "[bootstrap_module] Cannot cd:[${install_dir}] for installing module:[$module_name]"
+    $DO cd "${install_dir}" || die "Cannot cd:[${install_dir}] for installing module:[$module_name]"
 
     # 2. Retrieve remote distribution
     # $GIT_URL="ssh://git@github.com/franckporcher"
@@ -249,7 +249,7 @@ function bootstrap_module () {
     then
         # OK (empty dir) - can clone directly into it
         $DO $GIT clone --branch "${git_branch_name}" "$( git_url "${git_repos_name}" )" .   \
-            || die "[bootstrap_module] Cannot git clone ${git_repos_name}/${git_branch_name} into . ($!)"
+            || die "Cannot git clone ${git_repos_name}/${git_branch_name} into . ($!)"
 
         # Transfer ownership to WWW
         dirname="$(basename "$(pwd)")"
@@ -264,7 +264,7 @@ function bootstrap_module () {
         # Clone git repository into a new temporary sub directory
         tmpdir="__git_tmp_$(date "+%s")"
         $DO $GIT clone --branch "${git_branch_name}" "$( git_url "${git_repos_name}" )" "${tmpdir}" \
-            || die "[bootstrap_module] Cannot git clone ${git_repos_name}/${git_branch_name} into ${tmpdir} ($!)"
+            || die "Cannot git clone ${git_repos_name}/${git_branch_name} into ${tmpdir} ($!)"
         chown -R "${WWWUID}:${WWWGID}" "${tmpdir}"
 
         # Move everything into current directory
@@ -274,13 +274,13 @@ function bootstrap_module () {
     fi
 
     # 3. REC 
-    $DO rec_bootstrap_module "${git_repos_name}"    || die "[bootstrap_module] rec_bootstrap_module died: $!"
+    $DO rec_bootstrap_module "${git_repos_name}"    || die "die: $!"
 
     # 4. Post bootstrap 
     MUTINY_ROOT_INSTALL="${MUTINY_ROOT_INSTALL}" \
     DEFINES="${DEFINES}" \
     UTILS="${UTILS}" \
-    $DO _RUN_SCRIPT "${BOOTSTRAP_MODULE_POST}"      || die "_RUN_SCRIPT ${BOOTSTRAP_MODULE_POST} died: $!"
+    $DO _RUN_SCRIPT "${BOOTSTRAP_MODULE_POST}"      || die "die: $!"
 }
 
 
@@ -295,7 +295,7 @@ function bootstrap_module () {
 function rec_bootstrap_module () {
     module_name="$1"
 
-    [ -z "${module_name}" ] && die "[rec_bootstrap_module] Usage: rec_bootstrap_module <module_name>"
+    [ -z "${module_name}" ] && die "Usage: rec_bootstrap_module <module_name>"
 
     # 1. Get the repository name and the branch name to fetch
     for submodule in ${MODULES["${module_name}"]}
